export const tabs = [
  {
    code: 'uz',
    lang: 'O‘zbek tili',
    title: 'Sarlavha',
    price: 'Narx',
    message: "Xabar",
    publisher: 'Nashriyot',
    description: 'Tavsif',
    body: 'Matn',
    question: 'Savol matni',
    answer: 'Javob matni',
    name: 'Ism shariflari',
    location: 'Manzil',
    position: 'Ilmiy darajalari',
    major: 'Sohalari',
    author: 'Muallif',
    comment: 'Fikr-mulohaza',
    project: 'Nomi',
    country: 'Davlati',
    rank: 'Hazratning lavozimlari',
    doer: 'Ilmiy ishni qiluvchi shaxs',
    index: 1,
  },
  {
    code: 'ru',
    lang: 'Pусский язык',
    title: 'Название',
    price: 'Цена',
    message: "Сообщение",
    publisher: 'Издательский',
    description: 'Описание',
    body: 'Текст',
    question: 'Текст вопроса',
    answer: 'Текст ответа',
    name: 'Полное имя',
    location: 'Адрес',
    position: 'Ученая степень',
    major: 'Направление',
    author: 'Автор',
    comment: 'Обратная связь',
    project: 'Название',
    country: 'Страна',
    rank: 'Позиция мистера',
    doer: 'Человек, который занимается научной работой',
    index: 2,
  },
  {
    code: 'eng',
    lang: 'English',
    title: 'Title',
    price: 'Price',
    message: "Message",
    publisher: 'Publishing',
    description: 'Description',
    body: 'Text',
    question: 'Question text',
    answer: 'Answer text',
    name: 'Full name',
    location: 'Address',
    position: 'Academic degree',
    major: 'Field',
    author: 'Author',
    comment: 'Feedback',
    project: 'Name',
    country: 'Country',
    rank: 'Position of sir',
    doer: 'A person who does scientific work',
    index: 3,
  },
]
