export interface Staff {
   id: number,
   name: string,
   phone: string,
   password: string,
   role: {
      foods: boolean,
      categories: boolean,
      couriers: boolean,
      orders: boolean,
      users: boolean,
      branches: boolean,
      social: boolean,
      about: boolean,
      news: boolean,
      code: boolean,
   },
   token: string,
}
export interface Form {
   id: number | null,
   name: string | null,
   phone: string | null,
   password: string | null,
   role: {
      foods: boolean,
      categories: boolean,
      couriers: boolean,
      orders: boolean,
      users: boolean,
      branches: boolean,
      social: boolean,
      about: boolean,
      news: boolean,
      code: boolean,
   },
   token: string | null,
}
